# Generated by Django 2.2.7 on 2019-12-14 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mealdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_data', models.CharField(max_length=20, null=True)),
                ('meal_data', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
