# Generated by Django 2.2.7 on 2019-12-14 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealdata',
            name='date_data',
            field=models.IntegerField(null=True),
        ),
    ]
