# Generated by Django 2.2.7 on 2019-12-14 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsapi', '0002_auto_20191214_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealdata',
            name='id',
        ),
        migrations.AlterField(
            model_name='mealdata',
            name='date_data',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
